### ISSUE TITLE
Tag 1.0.1?

### ISSUE THREAD

**Issue by RobLoach** [madeofpeople/metalsmith-swig-helpers#6]
:+1: 

npm publish it live!!!

**Comment by thiagodemellobueno** [comment]
Been done for a while. https://www.npmjs.com/package/metalsmith-swig-helpers it's at 1.2.1 already.
Should I tag the latest release?

**Comment by thiagodemellobueno** [comment]
https://github.com/madeofpeople/metalsmith-swig-helpers/releases/tag/1.2.1

**Comment by RobLoach** [comment]
:dancers: :dancer: :dancers:
